### ISSUE TITLE
GPU not being used

### ISSUE THREAD

**Issue by somitgupta** [gw0/docker-keras-full#4]
Hi,
    I have been using gw000/keras-full:2.0.2 for a while now. I recently installed a new instance of gw000/keras-full:2.0.2 on my VM and I tried to run one of my old python scripts using Theano + python2 to train a DNN. When I check in the GPU usage in the VM using nvidia-smi I get 0MiB memory use. 

> Fri Dec 15 19:25:44 2017
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla K80           Off  | 00006BFB:00:00.0 Off |                    0 |
> | N/A   34C    P0    75W / 149W |      0MiB / 11439MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+

When I get into the docker instance and run nvidia-smi I get
 

> "Failed to initialize NVML: Driver/library version mismatch"

Seems like the docker instance is not able to use the GPU yet. What do you suggest I should do in this case?

**Comment by gw0** [comment]
As the error says, your Nvidia kernel driver and the library versions in this Docker container do not match. Different versions can not work together. Because there are so many combinations, the best way is to also install Nvidia libraries on your host machine (so that they match your kernel driver) and then mount those libraries (read-only) into the container. This can be accomplished with these additional parameters when starting the container:

```
$ docker run -d $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro') ...
```

If you are interested, what they represent, just pass them to the echo command. Like:

```
$ echo $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro')
--device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0 --device=/dev/nvidiactl -v /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so:ro -v /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro -v /usr/lib/x86_64-linux-gnu/libcudadevrt.a:/usr/lib/x86_64-linux-gnu/libcudadevrt.a:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so:/usr/lib/x86_64-linux-gnu/libcudart.so:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so.8.0:/usr/lib/x86_64-linux-gnu/libcudart.so.8.0:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44:/usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44:ro -v /usr/lib/x86_64-linux-gnu/libcudart_static.a:/usr/lib/x86_64-linux-gnu/libcudart_static.a:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.82:/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.82:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.82:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.82:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.82:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.82:ro
```

**Comment by somitgupta** [comment]
Thanks a lot of the reply. This helped. I realized that if you do [network deb install](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=debnetwork) of CUDA then it skips installing some libraries which default to an older version in the docker instance and lead to a version mismatch. I fixed it by installing CUDA on my VM through a [local runfile install ](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=runfilelocal)

Now I can see the output in the docker instance for 

>  nvidia-smi
Tue Dec 19 06:57:44 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 6BFB:00:00.0     Off |                    0 |
| N/A   34C    P0    73W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

But still there is a mismatch between the nvidia-smi version 375.39 and the driver version 387.26. This inhibits use of GPU. I get the following message in the logs: 

> tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 387.26.0 does not match DSO version 375.39.0 -- cannot find working devices in this configuration. 

Any suggestions on what I can do here?  

Seems like docker instance comes with its own set of nvidia libraries. Here are the libraries for the VM:

> $ echo $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro')
--device=/dev/nvidia0 --device=/dev/nvidiactl --device=/dev/nvidia-modeset --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -v /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so:ro -v /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro -v /usr/lib/x86_64-linux-gnu/libcuda.so.387.26:/usr/lib/x86_64-linux-gnu/libcuda.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.0.2:/usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.0.2:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-tls.so.387.26:ro

Here are the set of libraries in the docker. Note that it still contains copies of libraries from older version 375.39. 

> echo $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro')
--device=/dev/nvidia-modeset --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0 --device=/dev/nvidiactl -v /usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so:ro -v /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro -v /usr/lib/x86_64-linux-gnu/libcuda.so.387.26:/usr/lib/x86_64-linux-gnu/libcuda.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libcudadevrt.a:/usr/lib/x86_64-linux-gnu/libcudadevrt.a:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so:/usr/lib/x86_64-linux-gnu/libcudart.so:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so.8.0:/usr/lib/x86_64-linux-gnu/libcudart.so.8.0:ro -v /usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44:/usr/lib/x86_64-linux-gnu/libcudart.so.8.0.44:ro -v /usr/lib/x86_64-linux-gnu/libcudart_static.a:/usr/lib/x86_64-linux-gnu/libcudart_static.a:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.39:/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.39:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0:/usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.0.2:/usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.0.2:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.39:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.39:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.39:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.39:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.387.26:ro -v /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.387.26:/usr/lib/x86_64-linux-gnu/libnvidia-tls.so.387.26:ro

**Comment by gw0** [comment]
Yes, the base image comes with Debian versions of most packages.

Can you check if Nvidia versions and other things work if you use this base image (you need to docker build it yourself and add keras):

- https://github.com/gw0/docker-debian-cuda/blob/master/Dockerfile.ubuntu1704

**Comment by LlewellynS96** [comment]
@somitgupta Creating a symbolic link seems to fix the issue.

ln -s /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.39/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.26

**Comment by gw0** [comment]
I have refactored the CUDA image based on Debian 9 without any CUDA Driver libraries in order to prevent driver mismatch issues. Now it is necessary to inject them from the host OS.

Please try out the latest version and reopen the issue, if it does not work for you.

**Comment by somitgupta** [comment]
Thank you so much for fixing this. Unfortunately I am still having issues. 

After trying out the latest version (2.1.4). I tried a simple script mentioned @ https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell to check if keras can access the GPU. 
```
import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))
```
`InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'MatMul_5': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: MatMul_5 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a_5, b_5)]]`

It gave me an error indicating that it cannot access the GPU. 

In the docker logs I see the following:
`[I 21:41:40.624 NotebookApp] Kernel restarted: 3ef820a7-c4d2-4ae1-b82f-6d10fabe7315
[I 21:41:40.709 NotebookApp] Saving file at /Untitled Folder/CheckForGPU.ipynb
[I 21:41:41.462 NotebookApp] Adapting to protocol v5.1 for kernel 3ef820a7-c4d2-4ae1-b82f-6d10fabe7315
[I 21:41:41.463 NotebookApp] Restoring connection for 3ef820a7-c4d2-4ae1-b82f-6d10fabe7315:2c054690f22e42319e62276d601ece59
[I 21:41:41.463 NotebookApp] Replaying 14 buffered messages
2018-02-19 21:41:42.819695: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-19 21:41:42.825290: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-02-19 21:41:42.825349: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 0ed5484c3c90
2018-02-19 21:41:42.825371: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 0ed5484c3c90
2018-02-19 21:41:42.825642: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2018-02-19 21:41:42.825698: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.26  Thu Dec  8 18:36:43 PST 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
"""
2018-02-19 21:41:42.825731: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.26.0`

When I check the cuda library path in docker instance I get this. libcuda.so points to /usr/local/cuda-9.1/targets/x86_64-linux/lib/stubs/libcuda.so

```
ls -al /usr/lib/x86_64-linux-gnu/{libcuda,libnvidia}*
```

```
lrwxrwxrwx 1 root root       61 Feb 16 11:10 /usr/lib/x86_64-linux-gnu/libcuda.so -> /usr/local/cuda-9.1/targets/x86_64-linux/lib/stubs/libcuda.so
lrwxrwxrwx 1 root root       10 Feb 16 11:10 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so
-rwxr-xr-x 1 root root  8294408 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libcuda.so.375.26
-rwxr-xr-x 1 root root   157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so
-rwxr-xr-x 1 root root   157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1
-rwxr-xr-x 1 root root   157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.375.26
-rwxr-xr-x 1 root root 48276880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.26
-rwxr-xr-x 1 root root   142896 Jan 11 00:19 /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1
-rwxr-xr-x 1 root root   142896 Jan 11 00:19 /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0
-rwxr-xr-x 1 root root    29872 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.375.26
-rwxr-xr-x 1 root root 27265136 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.375.26
-rwxr-xr-x 1 root root   170192 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so
-rwxr-xr-x 1 root root   170192 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
-rwxr-xr-x 1 root root   170192 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.375.26
-rwxr-xr-x 1 root root   308296 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.26
-rwxr-xr-x 1 root root    94440 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so
-rwxr-xr-x 1 root root    94440 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1
-rwxr-xr-x 1 root root    94440 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.375.26
-rwxr-xr-x 1 root root 29073528 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.375.26
-rwxr-xr-x 1 root root   488800 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.375.26
-rwxr-xr-x 1 root root  1805096 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.375.26
-rwxr-xr-x 1 root root  1799336 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.375.26
-rwxr-xr-x 1 root root   207880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so
-rwxr-xr-x 1 root root   207880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1
-rwxr-xr-x 1 root root   207880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.375.26
lrwxrwxrwx 1 root root       66 Feb 16 11:10 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so -> /usr/local/cuda-9.1/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
lrwxrwxrwx 1 root root       15 Feb 16 11:10 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 -> libnvidia-ml.so
-rwxr-xr-x 1 root root  1197536 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.375.26
-rwxr-xr-x 1 root root  8646792 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
-rwxr-xr-x 1 root root  8646792 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.375.26
-rwxr-xr-x 1 root root  9157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.26
-rwxr-xr-x 1 root root    13080 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.375.26
```
When I do the same in the VM hosting the docker instance, I get a slightly different result. 

```
lrwxrwxrwx 1 root root       12 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       17 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.375.26
-rwxr-xr-x 1 root root  8294408 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libcuda.so.375.26
lrwxrwxrwx 1 root root       18 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so -> libnvidia-cfg.so.1
lrwxrwxrwx 1 root root       23 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1 -> libnvidia-cfg.so.375.26
-rwxr-xr-x 1 root root   157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.375.26
-rwxr-xr-x 1 root root 48276880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.375.26
lrwxrwxrwx 1 root root       28 Jan 11 00:19 /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1 -> libnvidia-container.so.1.0.0
-rwxr-xr-x 1 root root   142896 Jan 11 00:19 /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1.0.0
-rwxr-xr-x 1 root root 27265136 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.375.26
-rwxr-xr-x 1 root root    29872 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.375.26
lrwxrwxrwx 1 root root       21 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so -> libnvidia-encode.so.1
lrwxrwxrwx 1 root root       26 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1 -> libnvidia-encode.so.375.26
-rwxr-xr-x 1 root root   170192 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.375.26
-rwxr-xr-x 1 root root   308296 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.375.26
lrwxrwxrwx 1 root root       18 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so -> libnvidia-fbc.so.1
lrwxrwxrwx 1 root root       23 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1 -> libnvidia-fbc.so.375.26
-rwxr-xr-x 1 root root    94440 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.375.26
-rwxr-xr-x 1 root root 29073528 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.375.26
-rwxr-xr-x 1 root root   488800 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.375.26
-rwxr-xr-x 1 root root  1805096 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-gtk2.so.375.26
-rwxr-xr-x 1 root root  1799336 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-gtk3.so.375.26
lrwxrwxrwx 1 root root       18 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so -> libnvidia-ifr.so.1
lrwxrwxrwx 1 root root       23 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1 -> libnvidia-ifr.so.375.26
-rwxr-xr-x 1 root root   207880 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.375.26
lrwxrwxrwx 1 root root       17 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so -> libnvidia-ml.so.1
lrwxrwxrwx 1 root root       22 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 -> libnvidia-ml.so.375.26
-rwxr-xr-x 1 root root  1197536 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.375.26
lrwxrwxrwx 1 root root       26 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1 -> libnvidia-opencl.so.375.26
-rwxr-xr-x 1 root root  8646792 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.375.26
-rwxr-xr-x 1 root root  9157896 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.375.26
-rwxr-xr-x 1 root root    13080 Dec 19 21:59 /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.375.26
```
libcuda.so points to libcuda.so.375.26

I am not sure if that is the issue that is causing the error. I was trying to amend the symbolic link in the docker instance but I dont have permissions. 

```
$ ln -s libcuda.so test
ln: failed to create symbolic link 'test': Permission denied
```
Even apt-get update throws errors: 
```
$ apt-get update
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```
I hope I have not overlooked something obvious on my end that is causing this. Please have a look and let me know if I can do anything to get around this. Also, it would be great if we still have all permissions on the docker instance.

**Comment by somitgupta** [comment]
PS: I dont think I can re-open an issue that is closed by you. If you agree that this is still an issue, please re-open the issue.

**Comment by gw0** [comment]
The link `libcuda.so -> /usr/local/cuda-9.1/targets/x86_64-linux/lib/stubs/libcuda.so` is the dummy fallback that prevents crashing.

According to good security practices, the default user in the new image is a normal user `user`, not `root`. This is why you see the permission denied errors. To step into the container as another user pass the parameter `--user root`, like:

```
to start a new container as a different user
$ docker run -d $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro') -p 8888:8888 -v $(pwd):/srv --user root gw000/keras-full bash

or to step into an already running container:
$ docker exec -it -u root nameofcontainer bash
```

**Comment by somitgupta** [comment]
Thanks! That works!
